### ISSUE TITLE
Floating Temporal Coagulate

### ISSUE THREAD

**Issue by paricbat** [coolhotdogguy/Beginners-Circle-Game-Jam-3#5]
Create a Temporal Coagulate float animation

**Comment by cuddleworks** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Floating Temporal Coagulate](https://trello.com/c/l1aVzKNB/44-floating-temporal-coagulate)

**Comment by cuddleworks** [comment]
Added only a slight floating, because it didn't look that good
